services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: devlinks
      POSTGRES_PASSWORD: devlinks
      POSTGRES_DB: devlinks
    ports: ['5432:5432']
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U devlinks']
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
